In [3]:
import numpy as np

from skimage.util import view_as_blocks
from skimage.transform import rescale, resize, downscale_local_mean
from skimage.measure import block_reduce

# Resizing

Broadly speaking, resizing an image can either work as an interpolator or an aggregator.  Many functions are available in Python to do this including:

* [OpenCV's resize](https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/)
* Skimage's [rescale](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.rescale), [resize](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.resize), [downscale_local_mean](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.downscale_local_mean), [block_reduce](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.block_reduce)
* Ndimage's [zoom](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html)
* Scipy's [decimate](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html) and [resample](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.resample.html#scipy.signal.resample)
* Rasterio's [resample](https://rasterio.readthedocs.io/en/stable/topics/resampling.html) tools

# Block Sum

A block sum adds the values in an array with a given shape

In [14]:
# As a simple example, take a 25x25 array of ones.

pixels = np.ones((25,25))

block_size = (5, 5)
blocks = view_as_blocks(pixels, block_size)
block_sum = np.sum(blocks,axis=(0,1))

In [15]:
block_sum

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

In a netcdf:
    
~~~
image = rioxarray.open_rasterio(fn).squeeze(drop=True)
pixels = (image.data).astype(float)
pixels[pixels==-1] = np.nan

block_size = (10, 10)
blocks = view_as_blocks(pixels, block_size)
block_sum = np.sum(blocks, axis=(2, 3))
~~~

# skimage downscaled_local_mean

scikit image can provide a [downscaled local mean](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.downscale_local_mean), and related a [rescale](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.rescale) and [resize](https://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.resize).

In [18]:
pixels = np.ones((25,25))

block_size = (5, 5)
block_average = downscale_local_mean(pixels,block_size)
print(block_average)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# Of course the average is related to the sum!

print(np.prod(block_size)*block_average)

[[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]


## Block Reduce

In [4]:
from skimage.measure import block_reduce

pixels = np.ones((25,25))
block_reduce(pixels, block_size=(5,5), func=np.sum)

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])